### ISSUE TITLE
OTP consumer

### ISSUE THREAD

**Issue by arpunk** [billosys/kanin#6]
So far the wrapper is working perfectly, however I haven't been able to start using a gen_server as a consumer with the handle_info callbacks instead of the plain receive/loop logic that's on the README.

Do you guys have any example for making it work as an OTP service instead? I'm not having any luck with it. Thanks!

**Comment by arpunk** [comment]
Sorry for all the noise. I got it working this time reading carefully the official amqp_common libraries.

**Comment by billota** [comment]
Let us know if you think your discovery of getting the consumer working could:

1. be assisted in the kanin docs, or
1. might benefit from some LFE wrapping

**Comment by arpunk** [comment]
Yes, I do think that having an example of using a consumer as an gen_server would be nice to have. That's what I ended up using in order to spawn n workers via poolboy. It was a straight port from the Erlang examples thought.

So far that has been my most "advanced" use case since I'm consuming straight forward from the queue but in the following weeks I'm going to depend more on kanin and if I find anything odd I'll try to comment it ASAP.

**Comment by odacoder** [comment]
@arpunk Nice -- looking forward to it!

I'm going to start porting the tutorials over to gitbook. I really like the way that's been working on for the LFE project (I've been following the docs work there). I've tried it out, and the workflow is much better than the hacking I was doing (and got tired of) for the kanin tutorials. Hopefully this should breathe some new life into things...

**Comment by odacoder** [comment]
Heads-up: I've moved the tutorials into a gitbook:
 * http://billo.gitbooks.io/lfe-rabbitmq-tutorials/

No new content yet, but it's a lot prettier :-) Thanks to @ryugi for the super-sweet retro book covers she's doing for our manuals/LFE translations :-)
