### ISSUE TITLE
Cannot compile kanin 0.3.0

### ISSUE THREAD

**Issue by arpunk** [billosys/kanin#7]
After the `0.3.0` release of kanin, I am no longer able to compile it as a dependency:
```
==> kanin (compile)
Compiled src/kanin-chan.lfe
Compiled src/kanin-conn.lfe
Compiled src/kanin-util.lfe
Compiling /usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe failed:
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord connection.close_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord connection.unblocked)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord channel.close_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord exchange.declare_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord exchange.delete_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord exchange.bind_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord exchange.unbind_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord queue.bind_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord queue.unbind_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord basic.qos_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord basic.recover_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord tx.select)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord tx.select_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord tx.commit)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord tx.commit_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord tx.rollback)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord tx.rollback_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord confirm.select_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord file.qos_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord file.stage)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord stream.qos_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord dtx.select)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord dtx.select_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord dtx.start_ok)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord test.content)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_connection)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_channel)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_access)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_exchange)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_queue)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_tx)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_confirm)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_dtx)
/usr/home/arpunk/repos/ng/deps/kanin/src/kanin.lfe:9: error expanding (defrecord P_test)
ERROR: compile failed while processing /usr/home/arpunk/repos/ng/deps/kanin: rebar_abort
resources/make/rabbit.mk:33: recipe for target 'compile-proj' failed
gmake: *** [compile-proj] Error 1
```
It could be related to https://github.com/rvirding/lfe/issues/99#issuecomment-66304977

**Comment by odacoder** [comment]
I think I know what this might be ... support for the explicit versioning in the "app version" of a ``rebar.config`` file is being discouraged for LFE apps (it can make it impossible to use ``lfe.config``). 

Did you completely rebuild using 0.3.0? I mean, did you remove all deps and start fresh? That would explain it, since lfe 0.9.0 would have been downloaded in that case.

I'm going to do some testing at my end ...

**Comment by arpunk** [comment]
yes I did. I tried to start fresh. Im not in a computer atm so I cant help
you out.  Give me 45 mins and ill try it from my workstation.

**Comment by odacoder** [comment]
On Mon, Jan 26, 2015 at 12:23 PM, Ricardo Lanziano <notifications@github.com
> wrote:

> yes I did. I tried to start fresh.


Perfect -- that's good news and helps support the conclusion :-)


> Im not in a computer atm so I cant help
> you out. Give me 45 mins and ill try it from my workstation.
>

No worries! I think I've got it sorted .... updating the README and make
include now ...


> El ene 26, 2015 12:24 PM, "Odakotah LaBlanc" <notifications@github.com>
> escribió:
>
> > I think I know what this might be ... support for the explicit
> versioning
> > in the "app version" of a rebar.config file is being discouraged for LFE
> > apps (it can make it impossible to use lfe.config).
> >
> > Did you completely rebuild using 0.3.0? I mean, did you remove all deps
> > and start fresh? That would explain it, since lfe 0.9.0 would have been
> > downloaded in that case.
> >
> > I'm going to do some testing at my end ...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/billosys/kanin/issues/7#issuecomment-71499161>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/billosys/kanin/issues/7#issuecomment-71509899>.
>



-- 
~odakotah

**Comment by odacoder** [comment]
> Im not in a computer atm so I cant help
> you out. Give me 45 mins and ill try it from my workstation.

No worries! I think I've got it sorted .... updating the README and make
include now ...

**Comment by odacoder** [comment]
> Im not in a computer atm so I cant help
> you out. Give me 45 mins and ill try it from my workstation.

No worries! I think I've got it sorted .... updating the README and make
include now ...

**Comment by odacoder** [comment]
I've just pushed the instructions here:
 * https://github.com/billosys/kanin#dependencies-

Let me know how it goes, when you get a chance.

**Comment by arpunk** [comment]
I have lfetool `1.5.0-dev` (fresh install from the dev-v1 branch) installed but still I get the same error. I notice I had the LFE version specified to "0.9.0" so I tried to change it to ".*" but I got the same error.

Next step was using lcfg to overwrite the LFE version but now ljson is not getting installed due LFE version mismatchs. I don't know if ljson can also overwrite it's settings to use development LFE but it seems kind of a hassle.

**Comment by arpunk** [comment]
For the record, in order to properly compile and use kanin `0.2.0` I had to copy the `rabbit.mk` file to my proyects resources to be able to get the amqp libraries downloaded and installed. Also, I use FreeBSD and I had to change the tar flags, I mentioned here: https://github.com/billosys/kanin/issues/5

**Comment by arpunk** [comment]
Thanks for your help! At the end I understood why lcfg exists and submited a PR to lfex/ljson in order to remove the hard dependency on LFE v0.9.0: https://github.com/lfex/ljson/pull/4
